services:
  todo-flaskapp:
    build: .                   
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      mongo:
        condition: service_started   # ← ждём, пока mongo запустится (хорошая практика)
    restart: unless-stopped          # ← полезно для разработки: перезапускается при сбое

  mongo:
    image: mvertes/alpine-mongo:latest
    container_name: todo-mongo-1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db         # ←  volume DB
    restart: unless-stopped

volumes:
  mongo-data:                        # ← volume для данных MongoDB